# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jongwon Kim
title: Postdoctoral Researcher, POSTECH
email:  jongwon.kim@lstlab.org, pioneer0517@postech.ac.kr
# email_title: Email (Email title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  jongwonKim-1997
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: LST lab.
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: https://www.lstlab.org/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/jongwonkim.jpg
about_content: | # this will include new lines to allow paragraphs
    Hi, I'm Jongwon Kim. I recently completed my Ph.D. in Industrial and Management Engineering at POSTECH (August 2026) and am now a postdoctoral researcher at the POSTECH Future IT Innovation Lab. My research centers on time series foundation models: adapting them to diverse downstream tasks such as forecasting and anomaly detection, and applying them to real-world problems in manufacturing. I also work on probabilistic models, including Gaussian processes and Bayesian modeling, and their use in Bayesian optimization. Through collaborations with Samsung Electronics, SK Hynix, POSCO, and KETI, I work at the intersection of machine learning and Quality, Statistics, and Reliability (QSR).
#  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

#  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#    - Lists
#   - Tables
#    - <a href="google.com">Links</a>
#    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        title: Samsung electronics 
        caption: 
          2021.06 - 2022.01
        quote: >
           Probablistic modeling for part of manufacturing system.
        description: | # this will include new lines to allow paragraphs
          Project manager, probablistic model 
          
      - layout: right
        title: KETI 
        caption: 
           2021.07 - 2021.11 
           2022.07 - 2022.11
           2023.09 - 2023.11
        quote: >
           Fish probablistic modeling
        description: | # this will include new lines to allow paragraphs
          Project manager, association problem, survival analysis
          
         
      - layout: right
        title: POSCO 
        caption: 
          2023.03 - 2023.11
        quote: >
           Regression modeling
        description: | # this will include new lines to allow paragraphs
          Project manager, regression model
      
      - layout: right
        title: SK Hynix 
        caption: 
          2023.03 - 2023.10
          2024.03 - 2024.10
        quote: >
           Implemetning anomaly detection model based on timeseries sensor data.
        description: | # this will include new lines to allow paragraphs
          Project manager, timeseries anomaly detection          

      - layout: right
        title: Samsung research
        caption: 
          2024.05 - 2025.05
        quote: >
           Modeling graph neural network
        description: | # this will include new lines to allow paragraphs
          Project member, Graph modeling
          
      - layout: right
        title: Ministry of Trade, Industry and Resources 
        caption: 
          2025.08 - 2028.02
        quote: >
           Development of Core Technologies for Manufacturing Foundation Models.
        description: | # this will include new lines to allow paragraphs
          Project manager, timeseries foundation model 

         
      #- layout: left
      #  border: weak  # Value of `weak` will display a weak border below this item. # Any 
      #                # other value (or no value) means no border will be displayed
      #  title: Project name
      #  link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
      #  link_text: Link Text
      #  additional_links:
      #    - title:  Github page for project (eg. sproogen/modern-resume-theme)
      #      icon: fab fa-github
      #      url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
      #    - title:  Github page for project (eg. sproogen/modern-resume-theme)
      #      icon: fab fa-github
      #      url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
      #  quote: >
      #    Short overview of the project (optional)
      #  description: | # this will include new lines to allow paragraphs
      #    Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: NAVER
        sub_title: Internship
        caption: 2018.07 - 2018.08
        quote: >
          the Korea's largest IT company
        description: | # this will include new lines to allow paragraphs
          User feedback
      - layout: right
        title: SMARF
        sub_title: Internship
        caption: 2019.06 - 2019.08
        quote: >
          Start-up company for smart-farm
        description: | # this will include new lines to allow paragraphs
          Implement a bug classification model on small single-board computer. Collect bug data in the field.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: POSTECH
        sub_title: Industrial and Management Engineering and Mathematics B.A.
        caption: 2015.03 - 2020.02
        description: | # this will include new lines to allow paragraphs
          Double majors
      - layout: top-right
        title: POSTECH
        sub_title:  Industrial and Management Engineering M.S.
        caption: 2020.03 - 2022.02
        description: | # this will include new lines to allow paragraphs
          Thesis: Constrained Density-Based Spatial Clustering of Applications with Noise (DBSCAN) using Hyperparameter Optimization
      - layout: top-right
        title: POSTECH
        sub_title:  Industrial and Management Engineering Ph.D.
        caption: 2022.02 - 2026.08
        description: | # this will include new lines to allow paragraphs
          Thesis: Toward Robust Anomaly Detection with Time-Series Foundation Models: Improving Anomaly Separability through Provable Mean Separation and Variance Reduction
      - layout: top-right
        title: POSTECH 
        sub_title: Future IT Innovation Lab. Postdoc
        caption: 2026.09 - 
  - title: Publications
    layout: list
    content:
      - layout: top-right
        title:  A probabilistic fish growth model for a smart aquaculture system
        sub_title: KSII Transactions on Internet and Information Systems, 2024
        caption: "<b>Kim, J.</b>, Park, E., Cho, S., Kwon, K. and Ko, Y. M.*"
      - layout: top-right
        title: Constrained Density-Based Spatial Clustering of Applications with Noise (DBSCAN) using Hyperparameter Optimization
        sub_title:  Knowledge-Based Systems, 2025
        caption: "<b>Kim, J.</b>, Lee, H. Y. and Ko, Y. M.*"
      - layout: top-right
        title:  Complexity- and Statistics-Guided Anomaly Detection in Time Series Foundation Models
        sub_title: International Conference on Learning Representations (ICLR), 2026
        caption: "<b>Kim, J.</b>, Ko, Y. M.*, Yoon, S., Kim, Y., Kim, S. I., Tae, J."
      - layout: top-right
        title:  Online surface temperature monitoring system for semiconductor automated test equipment using local Gaussian process 
        sub_title: IEEE Transactions on Semiconductor Manufacturing, 2026
        caption: "<b>Kim, J.</b>, Baik, S. M., Yu, D., Kim, J., Ko, Y. M.*"
      - layout: top-right
        title:  Patch-based Memory Gate Model in Time Series Foundation Model
        sub_title: Transactions on Machine Learning Research (TMLR), 2026
        caption: "Yoon, S., <b>Kim, J.</b>, Ha, J. and Ko, Y. M.*"
  - title: Awards
    layout: list
    content:
      - layout: top-right
        title: 2020 POSECH OPEN INNOVATION BIG DATA CHALLENGE prize (1st)
        sub_title:  Time series prediction for solar power generation    
      - layout: top-right
        title: 2021 Korea Data Information Science Society Spring Conference Best Poster Award (1st)
        sub_title:  Constrained clustering via black box optimization
      - layout: top-right
        title: 2022 ICONI conference outstanding paper award
        sub_title: Receive award for the paper entitled "A probabilistic fish growth model for a smart aquaculture system" 
      - layout: top-right
        title: 2024 Postechian Fellowship
        sub_title: Receive scholarship with 6,000,000 won
      - layout: top-right
        title: 2026 PIURI Scholarship
        sub_title: Receive scholarship from POSTECH
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Book collector, Big fan of Nongshim Red Force (Korean e-sports team), 
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
